@baseURL = https://wom22-api2.azurewebsites.net

// get all services
GET {{baseURL}}/services

###

// create new service
POST {{baseURL}}/services
Content-Type: application/json

{
    "name": "Poop",
    "price": 33.2,
    "available": true
}